CREATE ROLE treasury_owner LOGIN PASSWORD 'treasury_owner_local' NOSUPERUSER CREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE treasury_app LOGIN PASSWORD 'treasury_app_local' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER DATABASE treasury OWNER TO treasury_owner;
